# Generated by Django 3.0.6 on 2020-07-17 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.Order'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Dish'),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Category'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='home.FoodItem'),
        ),
    ]
