# Generated by Django 3.0.6 on 2020-07-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='branch',
        ),
    ]
