# Generated by Django 3.0.6 on 2020-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('initiated', 'INITIATED'), ('payed', 'PAYED'), ('preparing', 'PREPARING'), ('delivered', 'DELIVERED')], default='pending', max_length=9),
        ),
    ]
