# Generated by Django 3.0.6 on 2020-07-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
