# Generated by Django 3.0.6 on 2020-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20200727_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('COM', 'completed'), ('CAN', 'cancelled')], default='COM', max_length=15),
            preserve_default=False,
        ),
    ]
